### ISSUE TITLE
Support cloud-sql-proxy in privileged eiam shell

### ISSUE THREAD

**Issue by jessesomerville** [jessesomerville/ephemeral-iam#53]

**Comment by kaseyreed** [comment]
@jessesomerville I wrote a [small script](https://gist.github.com/kaseyreed/de5adfdd5ed8f8ea2ececf6e812df9f7) which helps unblock folks needing this functionality. Pardon the hacky bash.

**Comment by jessesomerville** [comment]
Nice! This should be easy to extrapolate to a new command
